const SB_URL="https://cqpihcfgjocmwaqwiemi.supabase.co";const SB_KEY="sb_publishable_kDx8ysTXs-p6J3EN7PNO0Q_on-h2m_r";
const CHECKOUT="https://pay.kiwify.com.br/CUnAMR0";const DBKEY="g360_prod_v1";let session=null,deferredPrompt=null,saveTimer=null;
const money=v=>Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});const today=()=>new Date().toISOString().slice(0,10);const uid=()=>crypto.randomUUID?crypto.randomUUID():Math.random().toString(36).slice(2)+Date.now();
let db=JSON.parse(localStorage.getItem(DBKEY)||"null")||{accounts:[{id:"dinheiro",name:"Dinheiro"},{id:"pix",name:"PIX"},{id:"cartao",name:"Cartão"}],cashDays:{},tx:[],products:[],purchases:[],employees:[],punches:[],hr:[],fiscal:{company:{},docs:[]},settings:{revenueTarget:0,spendingLimit:0,prolaboreTarget:0},closures:[]};
function showSignup(){authGate.classList.add("hidden");signupGate.classList.remove("hidden")}function showLogin(){signupGate.classList.add("hidden");authGate.classList.remove("hidden")}
async function api(path,opt={}){const h={apikey:SB_KEY,"Content-Type":"application/json",...(opt.headers||{})};if(session?.access_token)h.Authorization="Bearer "+session.access_token;const r=await fetch(SB_URL+path,{...opt,headers:h});const t=await r.text();let d;try{d=t?JSON.parse(t):null}catch{d=t}if(!r.ok)throw new Error(d?.msg||d?.message||d?.error_description||d?.error||"Erro");return d}
async function hasPaidAccess(){const u=await api("/auth/v1/user");const email=(u?.email||"").toLowerCase();if(!email)return false;const r=await api("/rest/v1/gestao360_access?email=eq."+encodeURIComponent(email)+"&select=active,status");return Array.isArray(r)&&r.length>0&&r[0].active===true}
async function passwordLogin(email,password,statusEl){const d=await api("/auth/v1/token?grant_type=password",{method:"POST",body:JSON.stringify({email,password})});session=d;localStorage.setItem("g360_session",JSON.stringify(d));if(!(await hasPaidAccess())){if(statusEl)statusEl.textContent="Compra não localizada para este e-mail. Use o mesmo e-mail informado na Kiwify.";localStorage.removeItem("g360_session");session=null;return false}await openApp();return true}
async function signIn(){try{authStatus.textContent="Entrando...";await passwordLogin(loginEmail.value.trim().toLowerCase(),loginPassword.value,authStatus)}catch(e){authStatus.textContent=e.message}}
async function signUp(){try{let e=signupEmail.value.trim().toLowerCase(),p=signupPassword.value;if(!e||p.length<8||p!==signupPassword2.value)throw new Error("Confira e-mail e senha. A senha deve ter 8 caracteres ou mais.");signupStatus.textContent="Criando seu acesso...";const r=await fetch(SB_URL+"/functions/v1/gestao360-first-access",{method:"POST",headers:{"Content-Type":"application/json","apikey":SB_KEY},body:JSON.stringify({email:e,password:p})});const d=await r.json().catch(()=>({}));if(!r.ok){if(d?.code==="already_active"){signupStatus.textContent="Seu e-mail já foi confirmado. Entrando...";try{await passwordLogin(e,p,signupStatus);return}catch(err){throw new Error("Seu acesso já existe. Volte e entre com a senha que você criou anteriormente.")}}throw new Error(d?.error||"Não foi possível criar o acesso agora. Tente novamente.")}signupStatus.textContent="Acesso criado. Entrando...";await passwordLogin(e,p,signupStatus)}catch(e){signupStatus.textContent=e.message}}
async function signOut(){try{await api("/auth/v1/logout",{method:"POST"})}catch{}localStorage.removeItem("g360_session");location.reload()}
async function checkSession(){try{const r=localStorage.getItem("g360_session");if(!r)return;session=JSON.parse(r);await api("/auth/v1/user");if(!(await hasPaidAccess())){localStorage.removeItem("g360_session");session=null;return}await openApp()}catch{localStorage.removeItem("g360_session")}}
async function openApp(){authGate.classList.add("hidden");signupGate.classList.add("hidden");app.classList.remove("hidden");await loadCloud();renderNav();render()}
async function loadCloud(){try{let u=await api("/auth/v1/user");let r=await api("/rest/v1/gestao360_user_data?user_id=eq."+u.id+"&select=data");if(r?.[0]?.data&&Object.keys(r[0].data).length){db=r[0].data;localStorage.setItem(DBKEY,JSON.stringify(db))}}catch(e){console.warn(e)}}
function save(){localStorage.setItem(DBKEY,JSON.stringify(db));clearTimeout(saveTimer);saveTimer=setTimeout(cloudSave,700)}
async function cloudSave(){if(!session)return;try{let u=await api("/auth/v1/user");await api("/rest/v1/gestao360_user_data?on_conflict=user_id",{method:"POST",headers:{Prefer:"resolution=merge-duplicates,return=minimal"},body:JSON.stringify({user_id:u.id,data:db,updated_at:new Date().toISOString()})})}catch(e){console.warn(e)}}
window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredPrompt=e});async function installApp(){if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null}else alert("No celular, abra o menu do navegador e toque em Instalar aplicativo ou Adicionar à tela inicial.")}
async function forceUpdate(){if("serviceWorker"in navigator){for(const r of await navigator.serviceWorker.getRegistrations())await r.update()}let u=new URL(location.href);u.searchParams.set("v",Date.now());location.replace(u)}
if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js");